### ISSUE TITLE
v3.0 release includes outdated vendors directory

### ISSUE THREAD

**Issue by conlanpatrek** [HBLL-Collection-Development/omeka-s-any-cloud#39]
**Describe the bug**
When installing from zip, the included vendors directory includes the old League/Flysystem S3 Adapter. The classnames have changed, and the source code was correctly updated, however the vendors directory embedded in the released zipfile is outdated.

**To Reproduce**
1. Create a new omeka install
2. Install the v3.0 AnyCloud module from zip.
3. Configure it for Amazon S3
4. Attempt to upload or view a media.

**Expected behavior**
Uploading or viewing work.

**Screenshots**
White screen, 500. Logs attached below. AnyCloud is attempting to reference a classname that is not present in the vendors directory.

**Desktop (please complete the following information):**
- OS: \[e.g. iOS\] Linux, dockerized debian.
- Browser \[e.g. chrome, safari\] Chrome
- Version \[e.g. 22\] v.3.0

**Additional context**
relevant log:

```
2023-07-31T19:04:08+00:00 ERR (3): Error: Class "League\Flysystem\AwsS3V3\AwsS3V3Adapter" not found in /var/www/omeka/modules/AnyCloud/src/Service/File/Adapter/AwsAdapter.php:25
Stack trace:
#0 /var/www/omeka/modules/AnyCloud/src/Service/File/Store/AnyCloudFactory.php(60): AnyCloud\Service\File\Adapter\AwsAdapter->createAdapter(Object(Omeka\Settings\Settings))
#1 /var/www/omeka/modules/AnyCloud/src/Service/File/Store/AnyCloudFactory.php(79): AnyCloud\Service\File\Store\AnyCloudFactory->createAdapter(Object(AnyCloud\Service\File\Adapter\AwsAdapter))
#2 /var/www/omeka/modules/AnyCloud/src/Service/File/Store/AnyCloudFactory.php(45): AnyCloud\Service\File\Store\AnyCloudFactory->createAwsAdapter()
#3 /var/www/omeka/modules/AnyCloud/src/Service/File/Store/AnyCloudFactory.php(34): AnyCloud\Service\File\Store\AnyCloudFactory->createFilesystem()
#4 /var/www/omeka/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): AnyCloud\Service\File\Store\AnyCloudFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'AnyCloud\\File\\S...', NULL)
#5 /var/www/omeka/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate('AnyCloud\\File\\S...')
#6 /var/www/omeka/application/src/Api/Representation/AbstractResourceRepresentation.php(262): Laminas\ServiceManager\ServiceManager->get('Omeka\\File\\Stor...')
#7 /var/www/omeka/application/src/Api/Representation/MediaRepresentation.php(86): Omeka\Api\Representation\AbstractResourceRepresentation->getFileUrl('square', '329916a74248e77...', 'jpg')
#8 /var/www/omeka/application/src/Api/Representation/AbstractRepresentation.php(122): Omeka\Api\Representation\MediaRepresentation->thumbnailUrl('square')
#9 /var/www/omeka/application/src/View/Helper/Thumbnail.php(21): Omeka\Api\Representation\AbstractRepresentation->thumbnailDisplayUrl('square')
#10 /var/www/omeka/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(691): Omeka\View\Helper\Thumbnail->__invoke(Object(Omeka\Api\Representation\MediaRepresentation), 'square')
#11 /var/www/omeka/application/view/omeka/admin/media/browse.phtml(61): Omeka\Api\Representation\AbstractResourceEntityRepresentation->linkPretty()
#12 /var/www/omeka/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('/var/www/omeka/...')
#13 /var/www/omeka/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render(NULL)
#14 /var/www/omeka/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#15 /var/www/omeka/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#16 /var/www/omeka/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#17 /var/www/omeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#18 /var/www/omeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#19 /var/www/omeka/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#20 /var/www/omeka/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#21 /var/www/omeka/index.php(21): Laminas\Mvc\Application->run()
#22 {main}
```

**Recommended solution**
Just make sure you delete the vendors directory and reinstall before releasing a fix to this. It doesn't look like you're using build / release automation, so I suspect it was just a manual error, and not a caching issue.

Delete vendors, run `composer install` and rerelease.

**Comment by GitByrd** [comment]
We're having the same error. We are unable to update our current instance to Omeka 4  using AnyCloud 3.0.0 Amazon Storage.

**Comment by GitByrd** [comment]
While we're waiting for an official fix released from the developer, is there an easy way to manually fix the issue here? In the AwsAdaptor.php file, it says to use the old directory of use League\Flysystem\AwsS3V3\AwsS3V3Adapter; ... do we just change that line to another directory, or is it more systemic than that?

**Comment by conlanpatrek** [comment]
> While we're waiting for an official fix released from the developer, is there an easy way to manually fix the issue here? In the AwsAdaptor.php file, it says to use the old directory of use League\Flysystem\AwsS3V3\AwsS3V3Adapter; ... do we just change that line to another directory, or is it more systemic than that?

If you're familiar with composer, you can reinstall the modules dependencies via the command line. This is what I did to get this functional.

1. Extract the release zip
2. Delete the `vendors` folder from the newly extracted directory
3. Run `composer install` in that directory.

You should see your vendors directory reappear. Try installing this version of the module instead.

**Comment by GitByrd** [comment]
Thank you for your prompt response, I will give that a try.

**Comment by jonfackrell** [comment]
@GitByrd I'm updating the module package now and will upload it with the correct dependencies.

**Comment by jonfackrell** [comment]
@GitByrd will you try v3.0.1 and let me know if works now? I ran `composer install` and included the new vendor folder in the zip file.

**Comment by GitByrd** [comment]
I appreciate your quick turn-around in providing a version 3.0.1...however,
unfortunately, once I tried upgrading the module in Omeka, I received this
following error across my site: dev.schafferlibrarycollections.org

*Fatal error*: Uncaught Error: Class
'ComposerAutoloaderInit66584b4b8f72f95b94c3a6c1a95dafe7' not found in
/home/schaffer/
dev.schafferlibrarycollections.org/modules/AnyCloud/vendor/autoload.php:7
Stack trace: #0 /home/schaffer/
dev.schafferlibrarycollections.org/modules/AnyCloud/Module.php(37):
require() #1 /home/schaffer/
dev.schafferlibrarycollections.org/vendor/laminas/laminas-eventmanager/src/EventManager.php(319):
AnyCloud\Module->onBootstrap(Object(Laminas\Mvc\MvcEvent)) #2
/home/schaffer/
dev.schafferlibrarycollections.org/vendor/laminas/laminas-eventmanager/src/EventManager.php(171):
Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#3 /home/schaffer/
dev.schafferlibrarycollections.org/vendor/laminas/laminas-mvc/src/Application.php(154):
Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#4 /home/schaffer/
dev.schafferlibrarycollections.org/application/src/Mvc/Application.php(40):
Laminas\Mvc\Application->bootstrap(Array) #5
/home/schaffer/dev.schafferlibrarycoll in
*/home/schaffer/dev.schafferlibrarycollections.org/modules/AnyCloud/vendor/autoload.php
<http://dev.schafferlibrarycollections.org/modules/AnyCloud/vendor/autoload.php>*
on
line *7*



*Jenn G. Byrd*
Web Developer
----------------
Schaffer Library,
Union College
***@***.***
518.388.6063

**Comment by conlanpatrek** [comment]
Maybe needs a `composer dump autoload` in the anycloud directory?

**Comment by jonfackrell** [comment]
I would try composer dump auto load or even the original suggestion of
deleting the vendor directory and running composer install.

I am curious what version of PHP you’re running - perhaps that might be the
issue.

**Comment by GitByrd** [comment]
We are currently running on php 8.0. What I did was delete the entire
AnyCloud module folder on our site and reuploaded the unzipped 3.0.1 folder
via sftp.

**Comment by conlanpatrek** [comment]
If you'll forgive my blind hand waving.

🤔 I'm also suspicious maybe this error has to do with updating an installed module without uninstalling and reinstalling through the ui. I know Omeka does some interesting things with autoloading module dependencies and I have to wonder from this error if they're maybe caching the autoload classname in the database.

If that was the case, try toggling this module on and off on the modules page. (Install / uninstall, not enable / disable) If this theory has legs I'd suspect that would clear your error.

**Comment by conlanpatrek** [comment]
@jonfackrell I just installed your update and confirmed it's functional. Thanks for the turnaround on this.

@GitByrd I'm not able to reproduce your issue actually. I attempted to test my theory above just now, and the upgrade worked just fine. I do notice that the autoload classname(`ComposerAutoloaderInit66584b4b8f72f95b94c3a6c1a95dafe7 `) provided in the error is not the one that's bundled in the 3.0.1 zip (`ComposerAutoloaderInit31acc590a62c220067abe45844012b1c`), so I feel like that's a hint.

**Comment by CSSSchaffer** [comment]
Hmm, I deleted everything and re-uploaded 3.0.1 and I'm still getting this error when I configure the AWS credentials: 

/home/schaffer/dev.schafferlibrarycollections.org/vendor/laminas/laminas-form/src/Element.php on line 56

**Comment by jonfackrell** [comment]
Did the values save or does it not let you save the credentials?

**Comment by GitByrd** [comment]
@jonfackrell The values saved.

**Comment by jonfackrell** [comment]
Ok, I’ll take a look and see if I can reproduce that error.

**Comment by CSSSchaffer** [comment]
@jonfackrell the good news is that the module actually seems to be working. I refreshed that page with the error and I got the green "this module has been successfully configured" and all our images seem to be showing up correctly on the site.

**Comment by jaredhowland** [comment]
This appears to be resolved. Thank you @jonfackrell
